<!DOCTYPE html>
<html><head>
    <meta charset="utf-8">
    <title>{% block htmltitle %}{{ page_title }}{% endblock %}</title>
    {% block htmlhead %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/reset.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/text.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/style.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/extrastyle.css") }}">
    {% endblock %}
</head><body>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body></html>
