<!DOCTYPE html>
<html><head>
    <meta charset="utf-8">
    <title>{% block htmltitle %}{{ page_title }}{% endblock %}</title>
    {% block htmlhead %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/reset.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/text.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/style.css") }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('rhino-static', path="css/extrastyle.css") }}">

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    {% endblock %}
</head><body>

    {% if not user.is_anonymous() %}
    <div id="settings">
        <div id="settings-inner">
            {% block settings %}
                <div class="signin-services">
                    <span>Add another account:</span>
                    <a href="{{ url_for('signin-twitter') }}" title="Sign in with Twitter"><img src="{{ url_for('rhino-static', path='komodo/twitter_32.png') }}" width="32" height="32" alt="Twitter"></a>
                    <a href="{{ url_for('signin-typepad') }}" title="Sign in with TypePad"><img src="{{ url_for('rhino-static', path='img/typepad-komodo-style-20100311-32px.png') }}" width="32" height="32" alt="TypePad"></a>
                    <a href="{{ url_for('signin-flickr') }}" title="Sign in with Flickr"><img src="{{ url_for('rhino-static', path='komodo/flickr_32.png') }}" width="32" height="32" alt="Flickr"></a>
                </div>
            {% endblock %}
        </div>
    </div>

    <div id="bar">
        <div id="gear"><a href="#">&#9881;</a></div>
    </div>
    {% endif %}

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <script type="text/javascript">
    function spinGear(i) {
        i++;

        var gearAngle = (18 * i) % 360;

        var transform = 'rotate(' + gearAngle + 'deg)';
        var $gear = $('#gear');
        $gear.css({
            '-moz-transform': transform,
            '-webkit-transform': transform,
            'transform': transform,
        }).addClass('spinning');

        if (i == 20) {
            $gear.removeClass('spinning');
            return;
        }
        $gear.delay(40).queue(function (next) {
            spinGear(i);
            next();
        });
    }

    $(document).ready(function () {
        $('#gear').click(function () {
            $('#settings').animate({'height': $('#settings').height() ? '0px' : '200px'}, 'slow');
            spinGear(0);
            return false;
        });
    });
    </script>

</body></html>
