{% extends "rhino/base.jj" %}

{% block content %}

    <form method="POST" action="{{ url_for('login') }}">
        {% if csrf_token and csrf_token != 'NOTPROVIDED' %}
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        {% endif %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_p() }}
        <input type="submit" value="Sign in">
    </form>

{% endblock %}
